server:
  port: 8001
  servlet:
    context-path: /api/v1
spring:
  application:
    name: alticci-service
  datasource:
    url: jdbc:h2:mem:alticcidb
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
springdoc:
  show-actuator: true
  api-docs:
    path: alticci-service/v3/api-docs